version = 1
SPDX-PackageName = "Boomerstation"
SPDX-PackageSupplier = "Monkestation <https://monkestation.com>"
SPDX-PackageDownloadLocation = "https://github.com/Monkestation/BoomerStation14"

[[annotations]]
path = ["Resources/Audio/**", "Resources/Textures/**"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"

[[annotations]]
path = ["**.txt", "**.json"]
precedence = "aggregate"
SPDX-FileCopyrightText = "None"
SPDX-License-Identifier = "MIT"
