using System.Linq;
using System.Numerics;
using Content.Client.Administration.UI.CustomControls;
using Content.Shared._Monkestation.Administration;
using Content.Shared.Roles;
using Robust.Client.AutoGenerated;
using Robust.Client.GameObjects;
using Robust.Client.Graphics;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;
using Robust.Shared.Prototypes;
using Robust.Shared.Utility;

namespace Content.Client._Monkestation.Administration.UI.RoleTimeExemptionPanel;

[GenerateTypedNameReferences]
public sealed partial class RoleTimeExemptionPanel : DefaultWindow
{
    public event Action<RoleTimeExemptions>? RoleTimeExemptionSubmitted;
    private string? PlayerUsername { get; set; }

    // This is less efficient than just holding a reference to the root control and enumerating children, but you
    // have to know how the controls are nested, which makes the code more complicated.
    // Role group name -> the role buttons themselves.
    private readonly Dictionary<string, (Button, List<(Button, IPrototype)>)> _roleCheckboxes = new();
    private readonly ISawmill _sawmill;

    [Dependency] private ILogManager _logManager = default!;
    [Dependency] private IEntityManager _entMan = default!;
    [Dependency] private IPrototypeManager _protoMan = default!;

    private const string ExpandedArrow = "▼";
    private const string ContractedArrow = "▶";

    public RoleTimeExemptionPanel()
    {
        RobustXamlLoader.Load(this);
        IoCManager.InjectDependencies(this);
        _sawmill = _logManager.GetSawmill("admin.playtimeexemptionpanel");
        SubmitButton.OnPressed += SubmitButtonOnOnPressed;

        var departmentJobs = _protoMan.EnumeratePrototypes<DepartmentPrototype>()
            .OrderBy(x => x.Weight);
        foreach (var proto in departmentJobs)
        {
            var roles = proto.Roles.Select(x => _protoMan.Index(x))
                .OrderBy(x => x.ID);
            CreateRoleGroup(proto.ID, proto.Color, roles);
        }

        var antagRoles = _protoMan.EnumeratePrototypes<AntagPrototype>()
            .OrderBy(x => x.ID);
        CreateRoleGroup(AntagPrototype.GroupName, AntagPrototype.GroupColor, antagRoles);
    }

    /// <summary>
    /// Creates a "Role group" which stores information and logic for one "group" of roll exemptions.
    /// For example, all antags are one group, logi is a group, medical is a group, etc...
    /// </summary>
    private void CreateRoleGroup<T>(string groupName, Color color, IEnumerable<T> roles) where T : class, IPrototype
    {
        var outerContainer = new BoxContainer
        {
            Name = $"{groupName}GroupOuterBox",
            HorizontalExpand = true,
            VerticalExpand = true,
            Orientation = BoxContainer.LayoutOrientation.Vertical,
            Margin = new Thickness(4),
        };

        // Stores stuff like enable all and expand buttons.
        var roleGroupHeader = new BoxContainer
        {
            Orientation = BoxContainer.LayoutOrientation.Horizontal,
        };

        // Stores the role checkboxes themselves.
        var innerContainer = new GridContainer
        {
            Name = $"{groupName}GroupInnerBox",
            HorizontalExpand = true,
            Columns = 2,
            Visible = false,
            Margin = new Thickness(15, 5, 0, 5),
        };

        var roleGroupCheckbox = CreateRoleGroupHeader(groupName, roleGroupHeader, color, innerContainer);

        outerContainer.AddChild(roleGroupHeader);

        // Add the roles themselves
        foreach (var role in roles)
        {
            AddRoleCheckbox(groupName, role.ID, innerContainer, roleGroupCheckbox);
        }

        outerContainer.AddChild(innerContainer);

        RolesContainer.AddChild(new PanelContainer
        {
            PanelOverride = new StyleBoxFlat
            {
                BackgroundColor = color,
            },
        });
        RolesContainer.AddChild(outerContainer);
        RolesContainer.AddChild(new HSeparator());
    }

    private Button CreateRoleGroupHeader(string groupName,
        BoxContainer header,
        Color color,
        GridContainer innerContainer)
    {
        var roleGroupCheckbox = new Button
        {
            Name = $"{groupName}GroupCheckbox",
            Text = Loc.GetString("role-time-exemptions-role-group"),
            Margin = new Thickness(0, 0, 5, 0),
            ToggleMode = true,
        };

        // When this is toggled, toggle all buttons in this group so they match.
        roleGroupCheckbox.OnToggled += args =>
        {
            foreach (var role in _roleCheckboxes[groupName].Item2)
            {
                role.Item1.Pressed = args.Pressed;
            }
        };

        var hideButton = new Button
        {
            Text = Loc.GetString("role-time-exemptions-expand-roles") + " " + ContractedArrow,
            ToggleMode = true,
        };
        hideButton.OnPressed += args =>
        {
            innerContainer.Visible = args.Button.Pressed;
            ((Button)args.Button).Text = args.Button.Pressed
                ? Loc.GetString("role-time-exemptions-contract-roles") + " " + ExpandedArrow
                : Loc.GetString("role-time-exemptions-expand-roles") + " " + ContractedArrow;
        };
        header.AddChild(new Label
        {
            Text = groupName,
            Modulate = color,
            Margin = new Thickness(0, 0, 5, 0),
        });
        header.AddChild(roleGroupCheckbox);
        header.AddChild(hideButton);
        return roleGroupCheckbox;
    }

    /// <summary>
    /// Adds a toggle button specifically for one "role" in a "group"
    /// E.g. it would add the Chief Medical Officer "role" into the "Medical" group.
    /// </summary>
    private void AddRoleCheckbox(string group,
        string role,
        GridContainer roleGroupInnerContainer,
        Button roleGroupCheckbox)
    {
        var roleCheckboxContainer = new BoxContainer();
        var roleToggleButton = new Button
        {
            Name = role,
            Text = role,
            ToggleMode = true,
        };
        roleToggleButton.OnToggled += args =>
        {
            // Checks the role group checkbox if all the children are pressed
            if (args.Pressed && _roleCheckboxes[group].Item2.All(e => e.Item1.Pressed))
                roleGroupCheckbox.Pressed = args.Pressed;
            else
                roleGroupCheckbox.Pressed = false;
        };

        IPrototype rolePrototype;

        if (_protoMan.TryIndex<JobPrototype>(role, out var jobPrototype))
            rolePrototype = jobPrototype;
        else if (_protoMan.TryIndex<AntagPrototype>(role, out var antagPrototype))
            rolePrototype = antagPrototype;
        else
        {
            _sawmill.Error(
                $"Adding a role checkbox for role {role}: role is not a JobPrototype or AntagPrototype.");

            return;
        }

        // This is adding the icon before the role name
        // TODO: This should not be using raw strings for prototypes as it means it won't be validated at all.
        // // I know the ban manager is doing the same thing, but that should not leak into UI code.
        if (jobPrototype is not null && _protoMan.TryIndex(jobPrototype.Icon, out var iconProto))
        {
            var jobIconTexture = new TextureRect
            {
                Texture = _entMan.System<SpriteSystem>().Frame0(iconProto.Icon),
                TextureScale = new Vector2(2.5f, 2.5f),
                Stretch = TextureRect.StretchMode.KeepCentered,
                Margin = new Thickness(5, 0, 0, 0),
            };
            roleCheckboxContainer.AddChild(jobIconTexture);
        }

        roleCheckboxContainer.AddChild(roleToggleButton);

        roleGroupInnerContainer.AddChild(roleCheckboxContainer);

        _roleCheckboxes.TryAdd(group, (roleGroupCheckbox, []));
        _roleCheckboxes[group].Item2.Add((roleToggleButton, rolePrototype));
    }

    public void UpdatePanelState(RoleTimeExemptionPanelEuiState state)
    {
        PlayerNameLabel.Text = Loc.GetString("role-time-exemption-panel-header", ("username", state.PlayerName));
        PlayerUsername = state.PlayerName;

        if (state.Exemptions == null)
        {
            return;
        }

        var selectedIds = state.Exemptions.JobExemptions.Select(antagPrototype => antagPrototype.Id).ToHashSet();
        selectedIds.UnionWith(state.Exemptions.AntagExemptions.Select(antagPrototype => antagPrototype.Id));

        foreach (var group in _roleCheckboxes)
        {
            var all = true;
            foreach (var roleCheckbox in group.Value.Item2)
            {
                var roleSelected = selectedIds.Contains(roleCheckbox.Item2.ID);
                roleCheckbox.Item1.Pressed = roleSelected;
                all = all && roleSelected;
            }

            group.Value.Item1.Pressed = all;
        }
    }

    private void SubmitButtonOnOnPressed(BaseButton.ButtonEventArgs obj)
    {
        if (PlayerUsername == null)
        {
            _sawmill.Warning("Attempted to save role exemption without a username");
            return;
        }

        var jobList = new List<ProtoId<JobPrototype>>();
        var antagList = new List<ProtoId<AntagPrototype>>();

        if (_roleCheckboxes.Count == 0)
            throw new DebugAssertException("RoleCheckboxes was empty");

        foreach (var button in _roleCheckboxes.Values.SelectMany(departmentButtons => departmentButtons.Item2))
        {
            if (button.Item1 is { Pressed: true, Name: not null })
            {
                switch (button.Item2)
                {
                    case JobPrototype:
                        jobList.Add(button.Item2.ID);
                        break;
                    case AntagPrototype:
                        antagList.Add(button.Item2.ID);
                        break;
                }
            }
        }

        var exemptions = new RoleTimeExemptions(
            jobList,
            antagList
        );

        RoleTimeExemptionSubmitted?.Invoke(exemptions);
    }
}
