using System.Linq;
using System.Numerics;
using Content.Shared.Ghost;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Ghost.Controls
{
    [GenerateTypedNameReferences]
    public sealed partial class GhostTargetWindow : DefaultWindow
    {
        //private List<(string, NetEntity)> _warps = new(); // Monkestation edit old
        private List<(string, NetEntity, int)> _warps = new(); // Monkestation edit new
        private string _searchText = string.Empty;

        public event Action<NetEntity>? WarpClicked;
        public event Action? OnGhostnadoClicked;

        public GhostTargetWindow()
        {
            RobustXamlLoader.Load(this);
            SearchBar.OnTextChanged += OnSearchTextChanged;

            GhostnadoButton.OnPressed += _ => OnGhostnadoClicked?.Invoke();
        }

        public void UpdateWarps(IEnumerable<GhostWarp> warps)
        {
            // Server COULD send these sorted but how about we just use the client to do it instead
            /* Monkestation edit old
            _warps = warps
                .OrderBy(w => w.IsWarpPoint)
                .ThenBy(w => w.DisplayName, Comparer<string>.Create(
                    (x, y) => string.Compare(x, y, StringComparison.Ordinal)))
                .Select(w =>
                {
                    var name = w.IsWarpPoint
                        ? Loc.GetString("ghost-target-window-current-button", ("name", w.DisplayName))
                        : w.DisplayName;

                    return (name, w.Entity);
                })
                .ToList();
            */
            // Monkestation edit new start
            // Monkestation edit new end
            _warps = [];
            foreach (GhostWarp warp in warps)
            {
                var name = "";
                var type = 0; // Magic numbers my beloved
                if (warp.Mob)
                {
                    name = warp.DisplayName + (warp.Followers > 0 ? " f: " + warp.Followers : "");
                    if (warp.IsGhost)
                    {
                        type = 4;
                    }
                    else if (warp.IsDead)
                    {
                        type = 3;
                    }
                    else if (warp.Antagonist)
                    {
                        type = 2;
                    }
                    else
                    {
                        type = 1;
                    }
                }
                else
                {
                    name = Loc.GetString("ghost-target-window-current-button", ("name", warp.DisplayName));
                }
                _warps.Add((name, warp.Entity, type));
            }
        }

        public void Populate()
        {
            //ButtonContainer.RemoveAllChildren(); // Monkestation edit old
            // Monkestation edit new start
            AntagonistContainer.DisposeAllChildren();
            LivingContainer.DisposeAllChildren();
            DeadContainer.DisposeAllChildren();
            GhostContainer.DisposeAllChildren();
            MiscContainer.DisposeAllChildren();
            // Monkestation edit new end
            AddButtons();
        }

        private void AddButtons()
        {
            //foreach (var (name, warpTarget) in _warps) // Monkestation edit old
            // Monkestation edit new start
            int totalAntagonistLength = 0;
            int totalLivingLength = 0;
            int totalDeadLength = 0;
            int totalGhostLength = 0;
            int totalMiscLength = 0;
            foreach (var (name, warpTarget, type) in _warps)
            // Monkestation edit new end
            {
                Button currentButtonRef = new Button
                {
                    Text = name,
                    TextAlign = Label.AlignMode.Right,
                    /* Monkestation edit old start
                    HorizontalAlignment = HAlignment.Center,
                    VerticalAlignment = VAlignment.Center,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(340, 20),
                    ClipText = true,
                     * Monkestation edit old end */
                    // Monkestation edit new start
                    HorizontalAlignment = HAlignment.Left,
                    VerticalAlignment = VAlignment.Top,
                    SizeFlagsStretchRatio = 1,
                    MinSize = new Vector2(20, 20),
                    // Monkestation edit new end
                };

                currentButtonRef.OnPressed += _ => WarpClicked?.Invoke(warpTarget);
                currentButtonRef.Visible = ButtonIsVisible(currentButtonRef);

                //ButtonContainer.AddChild(currentButtonRef); // Monkestation edit old
                // Monkestation edit new start
                switch (type)
                {
                    case 0:
                        totalMiscLength++;
                        MiscContainer.AddChild(currentButtonRef);
                        continue;
                    case 1:
                        totalLivingLength++;
                        LivingContainer.AddChild(currentButtonRef);
                        continue;
                    case 2:
                        totalAntagonistLength++;
                        AntagonistContainer.AddChild(currentButtonRef);
                        continue;
                    case 3:
                        totalDeadLength++;
                        DeadContainer.AddChild(currentButtonRef);
                        continue;
                    case 4:
                        totalGhostLength++;
                        GhostContainer.AddChild(currentButtonRef);
                        continue;
                }
                // Monkestation edit new end
            }
            // Monkestation edit new start
            AntagonistHeading.Title = "Antagonists - (" + totalAntagonistLength + ")";
            LivingHeading.Title = "Alive - (" + totalLivingLength + ")";
            DeadHeading.Title = "Dead - (" + totalDeadLength + ")";
            GhostHeading.Title = "Ghosts - (" + totalGhostLength + ")";
            MiscHeading.Title = "Misc - (" + totalMiscLength + ")";
            // Only check these ones for visibility, since the others will preety much always be valid
            AntagBox.Visible = totalAntagonistLength > 0;
            DeadBox.Visible = totalDeadLength > 0;
            // Monkestation edit new end
        }

        private bool ButtonIsVisible(Button button)
        {
            return string.IsNullOrEmpty(_searchText) || button.Text == null || button.Text.Contains(_searchText, StringComparison.OrdinalIgnoreCase);
        }

        private void UpdateVisibleButtons()
        {
            //foreach (var child in ButtonContainer.Children) // Monkestation edit old
            foreach (var child in AntagonistContainer.Children) // Monkestation edit new
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
            // Monkestation addition start
            foreach (var child in LivingContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
            foreach (var child in GhostContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
            foreach (var child in MiscContainer.Children)
            {
                if (child is Button button)
                    button.Visible = ButtonIsVisible(button);
            }
            // Monkestation addition end
        }

        private void OnSearchTextChanged(LineEdit.LineEditEventArgs args)
        {
            _searchText = args.Text;

            UpdateVisibleButtons();
            // Reset scroll bar so they can see the relevant results.
            GhostScroll.SetScrollValue(Vector2.Zero);
        }
    }
}
